CREATE DATABASE Service

CREATE TABLE Users (
Id INT IDENTITY(1, 1) PRIMARY KEY,
Username VARCHAR(30) UNIQUE NOT NULL,
Password VARCHAR(50) NOT NULL,
Name VARCHAR(50),
Birthdate DATETIME2,
Age INT CHECK(Age >= 14 AND Age <= 110),
Email VARCHAR(50) NOT NULL
)

CREATE TABLE Departments (
Id INT IDENTITY(1, 1) PRIMARY KEY,
Name VARCHAR(50) NOT NULL
)

CREATE TABLE Employees (
Id INT IDENTITY(1, 1) PRIMARY KEY,
FirstName VARCHAR(25),
LastName VARCHAR(25),
Birthdate DATETIME2,
Age INT CHECK(Age >= 18 AND Age <= 110),
DepartmentId INT REFERENCES Departments(Id)
)

CREATE TABLE Categories (
Id INT IDENTITY(1, 1) PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
DepartmentId INT NOT NULL REFERENCES Departments(Id)
)

CREATE TABLE Status (
Id INT IDENTITY(1, 1) PRIMARY KEY,
Label VARCHAR(30) NOT NULL
)

CREATE TABLE Reports (
Id INT IDENTITY(1, 1) PRIMARY KEY,
CategoryId INT NOT NULL REFERENCES Categories(Id),
StatusId INT NOT NULL REFERENCES Status(Id),
OpenDate DATETIME2 NOT NULL,
CloseDate DATETIME2,
Description VARCHAR(200) NOT NULL,
UserId INT NOT NULL REFERENCES Users(Id),
EmployeeId INT REFERENCES Employees(Id)
)